Sintomas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bigdoc.urls')),
    path('admin/', admin.site.urls),
]

bigdoc/urls.py
from django.urls import path
from . import views

app_name = 'bigdoc'

urlpatterns = [
    path('', views.index, name='index')
]

bigdoc/models.py
from django.db import models

# Create your models here.


class Doenca(models.Model):
    nome = models.CharField(max_length=50, unique=True)
    ordem = models.PositiveIntegerField(unique=True)

    class Meta:
        ordering = ['nome']

    def __str__(self):
        return f"{self.nome}"


class Sintoma(models.Model):
    nome = models.CharField(max_length=50, unique=True)
    ordem = models.PositiveIntegerField(unique=True)

    class Meta:
        ordering = ['nome']

    def __str__(self):
        return f"{self.nome}"

bigdoc/views.py
from django.shortcuts import render

from .models import Sintoma
from .util import diagnosticar

# Create your views here.


def index(request):
    if request.method == 'POST':
        sintomas = request.POST.getlist("sintomas")
        diagnostico = diagnosticar(sintomas)

        return render(request, 'bigdoc/diagnostico.html', {
            'sintomas_list': sintomas,
            'diagnostico': diagnostico
        })

    return render(request, 'bigdoc/index.html', {
        'sintomas': Sintoma.objects.all(),
    })

bigdoc/templates/bigdoc/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'bigdoc/styles.css' %}">

  {% block head %}
  {% endblock %}

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  {% block body %}
  <nav class="navbar navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 h-1 fs-1" href="{% url 'bigdoc:index' %}">BigDoc</a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
      </ul>
    </div>
  </nav>
  <hr>
  {% endblock %}
</body>

</html>

bigdoc/templates/bigdoc/diagnostico.html
{% extends 'bigdoc/base.html' %}

{% block title %}Diagnostico - BigDoc{% endblock %}

{% block body %}
<main class="container">
  {{ block.super }}

  <h2 class="mt-5 text-center">Diagnóstico</h2>
  <p>Sintomas escolhidos:</p>

  <div class="row row-cols-auto justify-content-between gy-4">
    <div class="col-lg-9">
      {% for sintoma in sintomas_list %}
      <div class="d-inline-block m-1 p-2 bg-primary text-white rounded-3">
        {{ sintoma }}
      </div>
      {% endfor %}
    </div>

    <div class="col-lg-3 align-self-center text-end">
      <a class="btn btn-outline-warning" href="{% url 'bigdoc:index' %}">Mudar sintomas</a>
    </div>
  </div>

  <table class="table table-striped mt-5">
    <caption>Valores aproximados *</caption>
    <thead>
      <tr>
        <th>Doença</th>
        <th>%</th>
      </tr>
    </thead>
    <tbody>
      {% for key, value in diagnostico.items %}
      {% if value > 10 %}
      <tr>
        <td>{{ key }}</td>
        <td>{{ value }}</td>
      </tr>
      {% endif %}
      {% endfor %}
    </tbody>
  </table>
</main>
{% endblock %}

bigdoc/templates/bigdoc/index.html
{% extends 'bigdoc/base.html' %}
{% load static %}

{% block title %}BigDoc{% endblock %}

{% block head %}
<script src="{% static 'bigdoc/search.js' %}" async></script>
{% endblock %}

{% block body %}
<main class="container">
  {{ block.super }}

  <input type="search" id="search" placeholder="Pesquisar sintomas" class="form-control w-auto mt-5 mb-4">

  <div id="not-found" class="visually-hidden text-muted">
    <p class="d-inline">
      <i>Nenhum <b>sintoma </b>encontrado...</i>
    </p>
    <button id="btn-clear" class="btn btn-link"><i>Mostrar todos</i></button>
  </div>

  <form action="{% url 'bigdoc:index' %}" method="post">{% csrf_token %}

    {% for sintoma in sintomas %}
    <div class="form-check form-check-inline ps-0 mb-2">
      <input class="btn-check" type="checkbox" name="sintomas" id="{{ sintoma|slugify }}" value="{{ sintoma }}">
      <label class="btn btn-outline-primary" for="{{ sintoma|slugify }}">
        {{ sintoma }}
      </label>
    </div>
    {% endfor %}
    <div class="row-auto mt-3">
      <input class="btn btn-warning btn-lg" id="diagnosticar" type="submit" value="Diagnosticar">
    </div>
  </form>

  </body>
</main>
{% endblock %}